One step install
DeepLink-org/DIPU pull request #358
Opened 2023-10-25 07:38 UTC by Wrench-Git

This PR's target is to enable users install DIPU by "pip install ."

2023-11-01 02:34 UTC, lljbash requested changes

2023-11-03 02:13 UTC, Wrench-Git commented on dipu/CMakeLists.txt
> +#----------------------------------Build DIOPI submodule-------------------------------------------
这样reorganize的改动需要再弄一个PR里做吗？

2023-11-03 03:50 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/CMakeLists.txt
> +## makefile is foolish, the following code is a work around to avoid make file to run multiple kineto-build when using make -j N
```suggestion
## the following code is a work around to avoid makefile to run multiple kineto-build when using make -j N
```

2023-11-03 10:34 UTC, lljbash commented
> This PR's target is to enable users install DIPU by "pip install ."
> 
> THIS PR ASLO REQUIRE THE FOLLOWING CHANGE FOR thirdparty/kineto/libkineto/CMakeLists.txt @caikun-pjlab `if(NOT DEFINED KINETO_COMPILED_WITH_CXX11_ABI)` ` execute_process(` ` COMMAND` ` sh -x -c` ` "python -c 'import torch;print(1 if torch.compiled_with_cxx11_abi() else 0)'"` ` OUTPUT_VARIABLE KINETO_COMPILED_WITH_CXX11_ABI)` `endif()`

这个等变成 submodule 了以后就容易搞了吧

2023-11-03 10:39 UTC, caikun-pjlab approved these changes

2023-11-03 10:47 UTC, lljbash requested changes

2023-11-03 10:47 UTC, lljbash commented on dipu/third_party/CMakeLists.txt
> +else()
这个分支里应该处理找不到的情况
建议先拿 find_library 找一下，没找到的话报个fatal error，并且指示用户有哪些设置方式（包括 internal）。

2023-11-03 10:47 UTC, lljbash commented on dipu/CMakeLists.txt
> +  set(DIOPI_IMPL_OPT "")
有点迷惑了，加个注释解释一下？

2023-11-05 05:50 UTC, mrdanielw approved these changes

2023-11-06 08:08 UTC, lljbash approved these changes

2023-11-06 08:53 UTC, merged