dipu support communication profile
DeepLink-org/DIPU pull request #365
Opened 2023-10-26 01:06 UTC by caikun-pjlab

2023-10-26 05:53 UTC, lljbash requested changes

2023-10-26 05:53 UTC, lljbash commented on dipu/tests/python/unittests/test_profiler_communication.py
能不能参照 tests/python/README 的说明，把它改成标准的 DIPU test？

看起来这个测试无关 torch_dipu，所以必须要独立运行？如果是这样的话应该把它放到 individual_scripts 里面去。

2023-10-26 05:53 UTC, lljbash commented on dipu/tests/python/unittests/test_profiler_communication.py
> +from torch import nn
```suggestion
```

2023-10-26 06:38 UTC, caikun-pjlab commented on dipu/tests/python/unittests/test_profiler_communication.py
这个我看看咋优化哈。这么写的原因是import torch_dipu放到最前面，多卡测试会出现SIGABRT，原因还没定位，所以就先这么写了一个

2023-10-27 05:40 UTC, lljbash commented on dipu/tests/python/unittests/test_profiler_communication.py
我看到后面的 import torch_dipu 了，最后如果发现必须这么写的话放到 individual_scripts 里面去是没问题的（那里的 test 都是这样的），只是不能放在 unittest 里面

2023-10-27 07:43 UTC, caikun-pjlab commented on dipu/tests/python/unittests/test_profiler_communication.py
先移动到了 dipu/tests/python/individual_scripts/test_profiler_communication.py

2023-10-27 07:43 UTC, caikun-pjlab commented on dipu/tests/python/unittests/test_profiler_communication.py
> +from torch import nn
已修复，删除了重复的import

2023-10-30 01:33 UTC, lljbash approved these changes

2023-10-30 02:56 UTC, mrdanielw approved these changes

2023-10-30 03:11 UTC, merged

2023-10-30 03:11 UTC, fandaoyi commented on dipu/tests/python/unittests/test_profiler_communication.py
> 这个我看看咋优化哈。这么写的原因是import torch_dipu放到最前面，多卡测试会出现SIGABRT，原因还没定位，所以就先这么写了一个

这个我后续定位下吧, 这个问题祎竹 之前也发现过