add Interface in CMake for diopi_impl
DeepLink-org/DIPU pull request #398
Opened 2023-11-07 06:04 UTC by Wrench-Git

make the diopi_impl as an INTERFACE so users can decide whether to link it.
Use the following CMake args to not link libdiopi_impl.so
"WITH_DIOPI=OFF"

2023-11-07 07:30 UTC, caikun-pjlab approved these changes

2023-11-09 12:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/DeepLink-org/DIPU?pullRequest=398) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/DeepLink-org/DIPU?pullRequest=398) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: Wrench-Git<br/>:x: wiryls<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/DeepLink-org/DIPU?pullRequest=398) it.</sub>

2023-11-10 02:58 UTC, lljbash approved these changes

2023-11-10 07:15 UTC, lljbash requested changes
改回两个变量吧

2023-11-13 09:14 UTC, lljbash commented on dipu/third_party/CMakeLists.txt
> +  add_library(diopi_impl_lib SHARED IMPORTED GLOBAL)
这里似乎不用 global

2023-11-13 09:14 UTC, lljbash commented on dipu/third_party/CMakeLists.txt
> +  # the default path is hard-coded and not safe, better to use other methods
之前说这里还要检查 WITH_DIOPI_LIBRARY 如果是 internal 要报错

2023-11-14 03:34 UTC, lljbash approved these changes

2023-11-14 06:04 UTC, merged