Fix hf llama precision.
DeepLink-org/DIPU pull request #414
Opened 2023-11-10 11:19 UTC by pdx1989

Fix hf llama precision for ascend backend.

2023-11-10 11:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/DeepLink-org/DIPU?pullRequest=414) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/DeepLink-org/DIPU?pullRequest=414) before we can accept your contribution.<br/><hr/>**Pan Daoxin** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/DeepLink-org/DIPU?pullRequest=414) it.</sub>

2023-11-12 13:58 UTC, jinminxi104 requested changes

2023-11-12 14:47 UTC, jinminxi104 requested changes

2023-11-12 14:47 UTC, jinminxi104 commented on dicp/dicp/vendor/AscendGraph/codegen/load_and_run.py
> +        input = list(map(lambda x: x.to(dipu_device_str), images))
如果输入有标量，是不是应该回到修改前？

2023-11-12 14:47 UTC, jinminxi104 commented on dicp/dicp/vendor/AscendGraph/codegen/ascend.py
> +        global sym_in_args
这些global都在codegen里面有操作，codegen希望只有生成代码一个功能

2023-11-13 01:39 UTC, jinminxi104 commented on dicp/dicp/vendor/AscendGraph/codegen/load_and_run.py
> +        input = list(map(lambda x: x.to(dipu_device_str), images))
由于之前已经处理为都是tensor
assert判断一下全部是tensor

2023-11-13 07:24 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/codegen/ascend.py
> +        global sym_in_args
已经重新设计

2023-11-13 07:24 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/codegen/load_and_run.py
> +        input = list(map(lambda x: x.to(dipu_device_str), images))
done

2023-11-13 13:52 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        # for higher precision
已做修改

2023-11-14 02:11 UTC, zhaochaoxing commented on dicp/dicp/dynamo_bridge/op_transformer.py
> +    def symint_in_shape(self, shape):
utils里面有这个函数

2023-11-14 02:43 UTC, pdx1989 commented on dicp/dicp/dynamo_bridge/op_transformer.py
> +    def symint_in_shape(self, shape):
已复用

2023-11-14 03:31 UTC, tangzhiyi11 commented on dicp/dicp/vendor/AscendGraph/codegen/ascend.py
> +                                     tmp_arg = args[idx].clone()
这里是在做什么？

2023-11-14 03:31 UTC, tangzhiyi11 commented on dicp/dicp/vendor/AscendGraph/codegen/ascend.py
> +                if name in self.cpu_tensor:
什么情况下会有cpu tensor?

2023-11-14 03:31 UTC, tangzhiyi11 commented on dicp/dicp/vendor/AscendGraph/codegen/ascend.py
> +        call_body.writeline(f"args.clear()")
这里不用加 f

2023-11-14 03:31 UTC, tangzhiyi11 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        else:
这里不用cast，需要什么类型的就传入什么类型的就行了

2023-11-14 04:52 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/codegen/ascend.py
> +                if name in self.cpu_tensor:
有的cast('cpu')正好是图的输出，就需要这样

2023-11-14 04:54 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/codegen/ascend.py
> +        call_body.writeline(f"args.clear()")
done

2023-11-14 06:02 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/codegen/ascend.py
> +                                     tmp_arg = args[idx].clone()
处理非连续性tensor输入

2023-11-14 06:03 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        else:
现在通过判断输出类型的dtype已经对齐了

2023-11-14 10:12 UTC, tangzhiyi11 commented on dicp/dicp/vendor/AscendGraph/codegen/ascend.py
> +    def CastCpu(name, x, ascend_dtype, device=None):
改成 CastToCpu 好点？

2023-11-14 10:12 UTC, tangzhiyi11 commented on dicp/dicp/vendor/AscendGraph/codegen/ascend.py
> +
多个空行

2023-11-14 10:12 UTC, tangzhiyi11 commented on dicp/dicp/vendor/AscendGraph/codegen/load_and_run.py
> +            assert isinstance(img, torch.Tensor)
这里为什么要加 assert tensor ?

2023-11-14 10:12 UTC, tangzhiyi11 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        # TODO! MatMul not support fp32 input
“MatMul not support fp32 input” 这个不对吧，matmul 支持 fp32

2023-11-14 10:12 UTC, tangzhiyi11 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        return self.get_proxy(ascend_op.IdentityInp, (src, dst))
copy 就走正常的 identity 吧？

2023-11-14 10:12 UTC, tangzhiyi11 commented on dicp/dicp/vendor/AscendGraph/opset_convert.py
> +                if len(n.args) == 3 and n.args[2] is not None and n.args[2] == torch.device(type='cpu'):
op 类型匹配上了，下面的 if 判断就不需要了吧？

2023-11-14 10:15 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        # TODO! MatMul not support fp32 input
如果加上_keep_dtype=1的属性，就会报错fp32不支持了，看上去还是fp16的核心

2023-11-14 10:32 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/codegen/ascend.py
> +    def CastCpu(name, x, ascend_dtype, device=None):
done

2023-11-14 10:32 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/codegen/ascend.py
> +
done

2023-11-14 10:56 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/opset_convert.py
> +                if len(n.args) == 3 and n.args[2] is not None and n.args[2] == torch.device(type='cpu'):
已修改

2023-11-14 10:56 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        return self.get_proxy(ascend_op.IdentityInp, (src, dst))
done

2023-11-15 08:05 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        return self.get_proxy(ascend_op.IdentityInp, (src, dst))
done

2023-11-15 08:05 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/codegen/load_and_run.py
> +            assert isinstance(img, torch.Tensor)
已恢复原来的写法

2023-11-16 00:47 UTC, tangzhiyi11 approved these changes

2023-11-16 02:00 UTC, zhaochaoxing approved these changes

2023-11-16 02:24 UTC, zhaochaoxing commented on dicp/dicp/vendor/AscendGraph/codegen/ascend.py
> +    def CastToCpu(name, x, ascend_dtype, device=None):
Cast和CastToCpu看着没区别？

2023-11-16 02:32 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/codegen/ascend.py
> +    def CastToCpu(name, x, ascend_dtype, device=None):
这个主要是为了代码意义看上去更明显一些

2023-11-16 03:16 UTC, jinminxi104 approved these changes

2023-11-16 03:17 UTC, merged